version: "3"
services:
  node_api:
    container_name: node_api
    build:
        context: .
        dockerfile: Dockerfile_api
    volumes:
      - type: bind
        source: ./images
        target: /opt/app/backend/public/images
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - mongo
  node_worker:
    container_name: node_worker
    build:
        context: .
        dockerfile: Dockerfile_worker
    volumes:
      - type: bind
        source: ./images
        target: /opt/app/backend/public/images
    links:
      - mongo
      - node_api
  mongo:
    container_name: mongo
    image: mongo:6.0.3
    volumes:
      - ./data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
